cloud:
  aws:
    credentials:
      access-key: {액세스키 입력}
      secret-key: {비밀 액세스키 입력}
    s3:
      bucket: doh-contest-storage
    region:
      static: ap-northeast-2 # 리전 정보
    stack:
      auto: false # 기본 프로파일 공통 설정

spring:
  application:
    name: DohApplication  # 애플리케이션 이름
  datasource:
    url: jdbc:mysql://teamdb.cx6acq2ikt1l.ap-northeast-2.rds.amazonaws.com:3306/DOH
    username: abc3
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true

  # 파일 업로드 설정 추가
  servlet:
    multipart:
      max-file-size: 10MB    # 최대 파일 크기 10MB
      max-request-size: 10MB # 최대 요청 크기 10MB

# Thymeleaf 설정
thymeleaf:
  enabled: true
  cache: false # 개발시 새로고침하면 적용됨
  prefix: classpath:templates/
  suffix: .html
  check-template-location: true
  mode: HTML

# MyBatis 설정
mybatis:
  mapper-locations: classpath:/mapper/**/*Mapper.xml

# 서버 포트 설정
server:
  port: 8083

#30분 세션 유지
server.servlet.session.timeout: 1800s